export const AUTH_SUCCESS_CODES = {
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_TOKEN_REFRESH_SUCCESS: "AUTH_TOKEN_REFRESH_SUCCESS",
  AUTH_EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  AUTH_VERIFICATION_SENT: "AUTH_VERIFICATION_SENT",
  AUTH_PASSWORD_UPDATED: "AUTH_PASSWORD_UPDATED",
} as const;

export const AUTH_ERROR_CODES = {
  AUTH_INVALID_EMAIL: "AUTH_INVALID_EMAIL",
  AUTH_INVALID_PASSWORD: "AUTH_INVALID_PASSWORD",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_NOT_VERIFIED: "AUTH_NOT_VERIFIED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
} as const;
