export const SUCCESS_CODES = {
  // Generic
  DEFAULT: "SUCCESS",
  CREATED: "SUCCESS_CREATED",
  UPDATED: "SUCCESS_UPDATED",
  DELETED: "SUCCESS_DELETED",
  FETCHED: "SUCCESS_FETCHED",
} as const;

export const ERROR_CODES = {
  // Generic
  DEFAULT: "ERROR",
  BAD_REQUEST: "ERROR_BAD_REQUEST",
  UNAUTHORIZED: "ERROR_UNAUTHORIZED",
  FORBIDDEN: "ERROR_FORBIDDEN",
  NOT_FOUND: "ERROR_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "ERROR_INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "ERROR_VALIDATION_ERROR",
  CONFLICT: "ERROR_CONFLICT",
} as const;

export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export type ApiResponseCode = SuccessCode | ErrorCode;
