export const SUCCESS_CODES = {
  // Generic
  DEFAULT: "SUCCESS",
  CREATED: "SUCCESS_CREATED",
  UPDATED: "SUCCESS_UPDATED",
  DELETED: "SUCCESS_DELETED",
  FETCHED: "SUCCESS_FETCHED",

  // Auth Specific
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_TOKEN_REFRESH_SUCCESS: "AUTH_TOKEN_REFRESH_SUCCESS",
  AUTH_EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  AUTH_VERIFICATION_SENT: "AUTH_VERIFICATION_SENT",
  AUTH_PASSWORD_UPDATED: "AUTH_PASSWORD_UPDATED",

  // Organization Specific
  ORG_CREATED: "ORG_CREATED",
  ORG_UPDATED: "ORG_UPDATED",
  ORG_INVITATION_SENT: "ORG_INVITATION_SENT",
  ORG_INVITATION_ACCEPTED: "ORG_INVITATION_ACCEPTED",
  ORG_MEMBER_ROLE_UPDATED: "ORG_MEMBER_ROLE_UPDATED",
  ORG_MEMBER_REMOVED: "ORG_MEMBER_REMOVED",

  // User Specific
  USER_DATA_FETCHED: "USER_DATA_FETCHED",
  USER_DATA_UPDATED: "USER_DATA_UPDATED",
} as const;

export const ERROR_CODES = {
  // Generic
  DEFAULT: "ERROR",
  BAD_REQUEST: "ERROR_BAD_REQUEST",
  UNAUTHORIZED: "ERROR_UNAUTHORIZED",
  FORBIDDEN: "ERROR_FORBIDDEN",
  NOT_FOUND: "ERROR_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "ERROR_INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "ERROR_VALIDATION_ERROR",
  CONFLICT: "ERROR_CONFLICT",

  // Auth Errors
  AUTH_INVALID_EMAIL: "AUTH_INVALID_EMAIL",
  AUTH_INVALID_PASSWORD: "AUTH_INVALID_PASSWORD",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_NOT_VERIFIED: "AUTH_NOT_VERIFIED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",

  // Organization/Member Errors
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_ALREADY_MEMBER: "ORG_ALREADY_MEMBER",
  ORG_INVITATION_NOT_FOUND: "ORG_INVITATION_NOT_FOUND",
  ORG_INVITATION_EXPIRED: "ORG_INVITATION_EXPIRED",
  ORG_INVITATION_INVALID: "ORG_INVITATION_INVALID",
} as const;

export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export type ApiResponseCode = SuccessCode | ErrorCode;
