export const ORG_SUCCESS_CODES = {
  ORG_CREATED: "ORG_CREATED",
  ORG_UPDATED: "ORG_UPDATED",
  ORG_INVITATION_SENT: "ORG_INVITATION_SENT",
  ORG_INVITATION_ACCEPTED: "ORG_INVITATION_ACCEPTED",
  ORG_INVITATIONS_FETCHED: "ORG_INVITATIONS_FETCHED",
  ORG_INVITATION_REVOKED: "ORG_INVITATION_REVOKED",
  ORG_MEMBERS_FETCHED: "ORG_MEMBERS_FETCHED",
  ORG_MEMBER_ROLE_UPDATED: "ORG_MEMBER_ROLE_UPDATED",
  ORG_MEMBER_STATUS_UPDATED: "ORG_MEMBER_STATUS_UPDATED",
  ORG_MEMBER_REMOVED: "ORG_MEMBER_REMOVED",
  // Team codes
  TEAM_CREATED: "TEAM_CREATED",
  TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_DELETED: "TEAM_DELETED",
  TEAM_FETCHED: "TEAM_FETCHED",
  TEAMS_FETCHED: "TEAMS_FETCHED",
  TEAM_MEMBER_ADDED: "TEAM_MEMBER_ADDED",
  TEAM_MEMBERS_ADDED: "TEAM_MEMBERS_ADDED",
  TEAM_MEMBER_REMOVED: "TEAM_MEMBER_REMOVED",
  TEAM_MEMBERS_FETCHED: "TEAM_MEMBERS_FETCHED",
  MY_TEAMS_FETCHED: "MY_TEAMS_FETCHED",
} as const;

export const ORG_ERROR_CODES = {
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_ALREADY_MEMBER: "ORG_ALREADY_MEMBER",
  ORG_INVITATION_NOT_FOUND: "ORG_INVITATION_NOT_FOUND",
  ORG_INVITATION_EXPIRED: "ORG_INVITATION_EXPIRED",
  ORG_INVITATION_INVALID: "ORG_INVITATION_INVALID",
  // Team error codes
  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  TEAM_MEMBER_ALREADY_EXISTS: "TEAM_MEMBER_ALREADY_EXISTS",
  TEAM_MEMBER_NOT_FOUND: "TEAM_MEMBER_NOT_FOUND",
} as const;



