export const ORG_SUCCESS_CODES = {
  ORG_CREATED: "ORG_CREATED",
  ORG_UPDATED: "ORG_UPDATED",
  ORG_INVITATION_SENT: "ORG_INVITATION_SENT",
  ORG_INVITATION_ACCEPTED: "ORG_INVITATION_ACCEPTED",
  ORG_INVITATIONS_FETCHED: "ORG_INVITATIONS_FETCHED",
  ORG_INVITATION_REVOKED: "ORG_INVITATION_REVOKED",
  ORG_MEMBERS_FETCHED: "ORG_MEMBERS_FETCHED",
  ORG_MEMBER_ROLE_UPDATED: "ORG_MEMBER_ROLE_UPDATED",
  ORG_MEMBER_STATUS_UPDATED: "ORG_MEMBER_STATUS_UPDATED",
  ORG_MEMBER_REMOVED: "ORG_MEMBER_REMOVED",
} as const;

export const ORG_ERROR_CODES = {
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_ALREADY_MEMBER: "ORG_ALREADY_MEMBER",
  ORG_INVITATION_NOT_FOUND: "ORG_INVITATION_NOT_FOUND",
  ORG_INVITATION_EXPIRED: "ORG_INVITATION_EXPIRED",
  ORG_INVITATION_INVALID: "ORG_INVITATION_INVALID",
} as const;
