export const NOTIF_SUCCESS_CODES = {
  NOTIF_FETCHED: "NOTIF_FETCHED",
  NOTIF_UNREAD_COUNT: "NOTIF_UNREAD_COUNT",
  NOTIF_MARKED_READ: "NOTIF_MARKED_READ",
  NOTIF_ALL_MARKED_READ: "NOTIF_ALL_MARKED_READ",
  NOTIF_DELETED: "NOTIF_DELETED",
  NOTIF_CREATED: "NOTIF_CREATED",
} as const;

export const NOTIF_ERROR_CODES = {
  NOTIF_NOT_FOUND: "NOTIF_NOT_FOUND",
} as const;
